use anyhow::Result;

use super::ExportData;
use crate::types::Importance;

/// Export data to Markdown format
pub fn export(data: &ExportData) -> Result<String> {
    let mut md = String::new();

    // Header
    md.push_str("# Folio Export\n\n");
    md.push_str(&format!(
        "*Exported on {} | {} activities | {} accomplishments*\n\n",
        data.exported_at.format("%Y-%m-%d %H:%M UTC"),
        data.metadata.total_activities,
        data.metadata.total_accomplishments
    ));

    // Date range
    if let Some(ref range) = data.metadata.date_range {
        md.push_str(&format!(
            "**Period:** {} to {}\n\n",
            range.start.format("%Y-%m-%d"),
            range.end.format("%Y-%m-%d")
        ));
    }

    // Summary
    md.push_str("---\n\n");
    md.push_str("## Summary\n\n");

    if !data.metadata.projects.is_empty() {
        md.push_str(&format!("**Projects:** {}\n\n", data.metadata.projects.join(", ")));
    }

    if !data.metadata.employers.is_empty() {
        md.push_str(&format!("**Employers:** {}\n\n", data.metadata.employers.join(", ")));
    }

    // Accomplishments section
    if !data.accomplishments.is_empty() {
        md.push_str("---\n\n");
        md.push_str("## Accomplishments\n\n");

        for acc in &data.accomplishments {
            md.push_str(&format!("### {}\n\n", acc.title));

            if let Some(ref situation) = acc.situation {
                md.push_str(&format!("**Situation:** {}\n\n", situation));
            }

            if let Some(ref task) = acc.task {
                md.push_str(&format!("**Task:** {}\n\n", task));
            }

            if let Some(ref action) = acc.action {
                md.push_str(&format!("**Action:** {}\n\n", action));
            }

            if let Some(ref result) = acc.result {
                md.push_str(&format!("**Result:** {}\n\n", result));
            }

            // Metrics
            if !acc.metrics.is_empty() {
                md.push_str("**Metrics:**\n");
                for metric in &acc.metrics {
                    md.push_str(&format!("- {} {}\n", metric.value, metric.description));
                }
                md.push_str("\n");
            }

            // Skills
            if !acc.skills.is_empty() {
                md.push_str(&format!("**Skills:** {}\n\n", acc.skills.join(", ")));
            }

            // Generated bullets
            if !acc.generated_bullets.is_empty() {
                md.push_str("**Resume Bullets:**\n");
                for bullet in &acc.generated_bullets {
                    md.push_str(&format!("- {}\n", bullet));
                }
                md.push_str("\n");
            }

            md.push_str("---\n\n");
        }
    }

    // Activities section
    if !data.activities.is_empty() {
        md.push_str("## Activities\n\n");

        // Group by project
        let mut by_project: std::collections::HashMap<String, Vec<_>> = std::collections::HashMap::new();
        for activity in &data.activities {
            let project = activity.project.clone().unwrap_or_else(|| "(No Project)".to_string());
            by_project.entry(project).or_default().push(activity);
        }

        for (project, activities) in by_project {
            md.push_str(&format!("### {}\n\n", project));

            for activity in activities {
                let importance_marker = match activity.importance {
                    Importance::High => "🔴",
                    Importance::Medium => "🟡",
                    Importance::Low => "⚪",
                };

                md.push_str(&format!(
                    "- {} **{}** ({})\n",
                    importance_marker,
                    activity.title,
                    activity.timestamp.format("%Y-%m-%d")
                ));

                if let Some(ref desc) = activity.description {
                    md.push_str(&format!("  - {}\n", desc));
                }

                if let Some(impact) = activity.metadata.get("impact").and_then(|v| v.as_str()) {
                    md.push_str(&format!("  - *Impact: {}*\n", impact));
                }
            }

            md.push_str("\n");
        }
    }

    // Footer
    md.push_str("---\n\n");
    md.push_str(&format!("*Generated by Folio v{}*\n", data.version));

    Ok(md)
}

/// Export as a brag document (simplified format)
pub fn export_brag_doc(data: &ExportData) -> Result<String> {
    let mut md = String::new();

    md.push_str("# Brag Document\n\n");

    if let Some(ref range) = data.metadata.date_range {
        md.push_str(&format!(
            "**Period:** {} - {}\n\n",
            range.start.format("%B %Y"),
            range.end.format("%B %Y")
        ));
    }

    md.push_str("## Key Accomplishments\n\n");

    // High importance items first
    let high_importance: Vec<_> = data.activities
        .iter()
        .filter(|a| matches!(a.importance, Importance::High))
        .collect();

    if !high_importance.is_empty() {
        for activity in high_importance {
            md.push_str(&format!("### {}\n\n", activity.title));

            if let Some(ref desc) = activity.description {
                md.push_str(&format!("{}\n\n", desc));
            }

            if let Some(impact) = activity.metadata.get("impact").and_then(|v| v.as_str()) {
                md.push_str(&format!("**Impact:** {}\n\n", impact));
            }

            if let Some(ref project) = activity.project {
                md.push_str(&format!("*Project: {}*\n\n", project));
            }
        }
    }

    // Other notable work
    let medium_importance: Vec<_> = data.activities
        .iter()
        .filter(|a| matches!(a.importance, Importance::Medium))
        .collect();

    if !medium_importance.is_empty() {
        md.push_str("## Other Notable Work\n\n");

        for activity in medium_importance.iter().take(10) {
            md.push_str(&format!("- **{}**", activity.title));
            if let Some(impact) = activity.metadata.get("impact").and_then(|v| v.as_str()) {
                md.push_str(&format!(" - {}", impact));
            }
            md.push_str("\n");
        }
        md.push_str("\n");
    }

    Ok(md)
}

/// Export as resume bullets
pub fn export_resume_bullets(data: &ExportData) -> Result<String> {
    let mut md = String::new();

    md.push_str("# Resume Bullets\n\n");

    // From accomplishments first (higher quality)
    if !data.accomplishments.is_empty() {
        md.push_str("## Polished Bullets\n\n");
        for acc in &data.accomplishments {
            for bullet in &acc.generated_bullets {
                md.push_str(&format!("- {}\n", bullet));
            }
        }
        md.push_str("\n");
    }

    // From activities
    md.push_str("## From Activities\n\n");

    for activity in data.activities.iter().filter(|a| matches!(a.importance, Importance::High | Importance::Medium)) {
        let mut bullet = activity.title.clone();

        // Add impact if available
        if let Some(impact) = activity.metadata.get("impact").and_then(|v| v.as_str()) {
            if !bullet.contains(&impact.to_lowercase()) {
                bullet = format!("{}, resulting in {}", bullet, impact.to_lowercase());
            }
        }

        // Ensure starts with capital
        if let Some(c) = bullet.chars().next() {
            if c.is_lowercase() {
                bullet = c.to_uppercase().to_string() + &bullet[1..];
            }
        }

        md.push_str(&format!("- {}\n", bullet));
    }

    Ok(md)
}
