mod capture;
mod config_cmd;
mod delete;
mod digest;
mod edit;
mod export_cmd;
mod list;
mod match_cmd;
mod promote;
mod search;
mod serve;
mod show;
mod stats;
mod sync;
mod tui_cmd;
mod watch;

pub use capture::run as capture;
pub use config_cmd::{run as config, init as config_init};
pub use delete::run as delete;
pub use digest::{run as digest, review as review};
pub use edit::run as edit;
pub use export_cmd::{run as export, import};
pub use list::run as list;
pub use match_cmd::run as match_job;
pub use promote::run as promote;
pub use search::run as search;
pub use serve::{run_api as serve_api, run_mcp as serve_mcp};
pub use show::run as show;
pub use stats::run as stats;
pub use sync::run as sync;
pub use tui_cmd::run as tui;
pub use watch::run as watch;
